version: '3.8'
services:
  aspnet:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:90"

  react:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Измените на 3000
  nginx:
    image: nginx:alpine
  
    ports:
      - "90:90"
    depends_on:
      - aspnet
      - react