server {
    listen 80;

    server_name sfrudn.local.com;
    location / {
        proxy_pass http://localhost:5000; # Порт ASP.NET приложения
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;

    server_name analitic.sfrudn.com;
    location / {
        root /app/wwwroot; # Путь к собранному React приложению
        try_files $uri /index.html;
    }
}